version: "3.8"
services:
  # 如果有现成的 Postgresql 实例，可以删除这一小节
  postgres:
    image: postgres:14-alpine
    container_name: postgresql_q2tg
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  zinclabs:
    volumes:
      - './zinc/data:/data'
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=password
      - ZINC_PLUGIN_GSE_ENABLE=true
      - ZINC_PLUGIN_GSE_DICT_EMBED=big
    container_name: zincsearch
    image: 'public.ecr.aws/zinclabs/zinc:latest'
    restart: unless-stopped
  q2tg:
    image: ghcr.io/nofated095/q2tg:rainbowcat
    container_name: main_q2tg
    restart: unless-stopped
    depends_on:
      - postgres
      - zinclabs
    volumes:
      - ./data:/app/data
    environment:
      - TG_API_ID=
      - TG_API_HASH=
      - TG_BOT_TOKEN=
      - DATABASE_URL=postgres://user:password@postgres/db_name
      - CRV_API=
      - CRV_KEY=
      - ZINC_URL=http://zinclabs:4080
      - ZINC_USERNAME=admin
      - ZINC_PASSWORD=password
      # 要支持转发时自动识别语音，请设置以下参数
      - BAIDU_APP_ID=
      - BAIDU_API_KEY=
      - BAIDU_SECRET_KEY=
      # 如果需要通过代理联网，那么设置下面两个变量
      #- PROXY_IP=
      #- PROXY_PORT=
